# Generated by Django 6.0.6 on 2026-06-16 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MonitoredURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='HealthCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('response_time', models.FloatField(blank=True, null=True)),
                ('is_up', models.BooleanField(default=False)),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('monitored_url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checks', to='monitor_app.monitoredurl')),
            ],
        ),
    ]
